### ISSUE TITLE
C/C++ toolchain story?

### ISSUE THREAD

**Issue by wingo** [WebAssembly/stack-switching#4]
Hi :)  Really looking forward to this for languages like Lua, Scheme, Swift, and such -- languages that provide deep lightweight threads.  If I understand some of the draft documents, the proposal as specified is enough to implement concurrent ML; for reference, [an overview of cml concurrency primitives and how to build them with delimited continuations](https://wingolog.org/archives/2017/06/29/a-new-concurrent-ml), and [an implementation in lua in terms of its coroutine primitives](https://wingolog.org/archives/2018/05/16/lightweight-concurrency-in-lua).

I was looking to see if we could target this with [C++20's coroutines](https://en.cppreference.com/w/cpp/language/coroutines).  I... don't think so?  C++'s coroutines are shallow and promise-based, like JavaScript's.  So what's the C/C++ story?  I guess you could implement [libmprompt](https://github.com/koka-lang/libmprompt) in terms of the stack switching primitives, but then you run into other problems, like the lack of delimited dynamic binding.

**Comment by dhil** [comment]
Hi Andy, good to see you here!

Thanks for your interest and question regarding C++
coroutines. Compilation of C++-style coroutines using our typed
continuations proposal is definitely something that is on our radar
and that we are actively discussing.

> I was looking to see if we could target this with C++20's
  coroutines. I... don't think so?

I think it is possible, though, I have not worked out all the details
yet. It is tricky to encode the symmetric transfer of control. As it
stands now, our proposal lends itself much more towards the asymmetric
style of coroutines. It may be that a new primitive is required in
order to implement symmetric coroutines efficiently, though, we
certainly need more experimentation before we can draw any
conclusions.

In the foreseeable future we do plan to perform more experiments with
encodings of control operators, such as C++ coroutines, using our
proposed primitives, however, so far we have only looked at
shift/reset, async/await, and lightweight threads á la Erlang.

> C++'s coroutines are shallow and promise-based [..]

I don't know what you mean by **shallow** in this context.

> I guess you could implement libmprompt in terms of the stack
  switching primitives, but then you run into other problems, like the
  lack of delimited dynamic binding.

I definitely think libmprompt is encodable using the current set of
proposed primitives. Again, a relevant question is whether such an
encoding can be efficient.

I don't know what you mean by the lack of delimited dynamic binding;
surely you can encode delimited dynamic binding using the proposed
primitives.

**Comment by wingo** [comment]
Heya @dhil :)  Thanks for the response!

Firstly I may be misunderstanding many things, among them some of the concrete aspects of the current stack switching proposal; is there a concrete draft somewhere?  Corrections very welcome.

I called C++20 coroutines "shallow" in the sense that they are for a single function activation rather than an arbitrary stack of activations, like JavaScript async functions or generators ([original rationale for JS, FWIW](http://calculist.org/blog/2011/12/14/why-coroutines-wont-work-on-the-web/)).  Perhaps this is abusing a term, though!

It's true that you certainly could implement a single-frame (shallow) coroutine with stack-capturing primitives but it doesn't seem to buy much; the proposal isn't necessary, given that there are straightforward local transformations that LLVM can do that don't require WebAssembly extensions.  On the other hand, it seems to my ignorant mind that given multi-frame (deep) coroutine primitives, you may want to support different programming models -- i.e. not that ["A coroutine is a function that can suspend execution to be resumed later"](https://en.cppreference.com/w/cpp/language/coroutines) but rather a coroutine is a continuation delimited by a prompt and a yield, as libmprompt provides.

For clarity, I was thinking of [Delimited dynamic binding](https://homes.luddy.indiana.edu/ccshan/dynscope/DDBinding.pdf), ICFP 2006.  I agree you can provide a thread abstraction that provides this facility, in terms of a global association between thread ID and binding set, and setting the current thread ID before resuming a coroutine.  You are right, that is probably sufficient.

**Comment by fgmccabe** [comment]
Hi Andy,
  Some responses.
1. There are a couple of sketches for proposals for wasm-level stack switching primitives. However, none of these should be viewed with any degree of certainty.
2. We have been recently focusing on a JS API. This is for a number of reasons, it allows an important class of applications to be unblocked more quickly, and it allows implementation effort to proceed in parallel with a more comprehensive look at wasm-level features. This has recently been inaugurated into its own repo https://github.com/WebAssembly/js-promise-integration
3. C++ coroutines should not be confused with anything that we are working on. As you noted, they are 'shallow'. I believe this is to allow implementations on existing compiler/ABI platforms.
4. Within the V8 team we have been investigating implementation of delimited continuations; most of the effort has been under the covers as it were: looking at how to extend the engine in what is arguably an extremely sensitive direction. We recently showed our [design portfolio](https://docs.google.com/document/d/16Us-pyte2-9DECJDfGm5tnUpfngJJOc8jbj54HMqE9Y/edit?usp=sharing).

**Comment by slindley** [comment]
Hi @wingo.

@rossberg, @dhil, and I have been playing around with a small extension of the Wasm reference interpreter with support for typed continuations here:
https://github.com/effect-handlers/wasm-spec/

We haven't yet thought deeply about how well C++ coroutines fit this design (and as @fgmccabe suggests, C++ coroutines have not been part of the general stack switching discussion so far). But, as @dhil says, this is certainly something that @dhil and I, at least, are interested in understanding better, alongside a whole swathe of other weird and wonderful control abstractions.

**Comment by wingo** [comment]
Thanks for your thoughts @fgmccabe & @slindley :)  The possibility of getting some form of delimited continuations in WebAssembly sounds absolutely delightful and it is really great to see your efforts in this area.

FWIW the context is that I am in the process of figuring out 2022 work plans at Igalia.  We have been trying to tie WebAssembly feature work into C++-on-the-web use cases.  When we can manage to line that up, we have the business case to move features forward that can also provide facilities for non-C++ languages.  So my real question was, is there a way in which this work can relate to an asynchronous C++ use case, whether through C++20 coroutines or otherwise?

If I understand what you are saying, and thinking about the C++-on-the-web use-case, then:
 1. Stack switching would not relate directly to pthreads and not to coroutines.
 2. You could maybe implement some fibers-like facility in c++ using libmprompt, and if you did, the mprompt api might be implementable via stack switching for the webassembly target
 3. In a more short-term sense, you could use stack switching as an implementation of asyncify, instead of the AOT transformation; i.e. the entry points to the module all start coroutines, allowing calls from C++ to promise-yielding JS functions to cause the entry point of the WebAssembly module to suspend.

Is this correct?  In that case I think the answer is more clear to me.

FWIW @fgmccabe I was able to view the "wrapper" document of the design portfolio but none of the linked documents, as they do not appear to be readable to me, though I did request access.

**Comment by fgmccabe** [comment]
Specifically on C++ async: this is one of the primary use cases. However, our thinking is that (in the zeroth instance), you will take your regular synchronous C++ code and use the JS Promise integration API to asyncify (sic) it. This is essentially a higher performance approach than using the asyncify tool itself.

Later on, when we have first class continuations in wasm, then you will be able to see how to use it in C++. But, as far as I understand, C++ does not have a good hook to hang this on. 

As for libmprompt, I am not sure of the utility of implementing it in wasm. That would essentially require gutting it and offer a reimplementation of its API. In particular, we are not likely to have the same performance characteristics.

As for the design docs, they have been made publicly accessible now. You should be able to access them via the embedded links. Please let me know if you cant.

**Comment by wingo** [comment]
Thanks again @fgmccabe, the design portfolio makes it all clear to me.

To answer the original question, the C++ toolchain story is:
 1. For many uses, we can mostly avoid touching the toolchain, and instead use the JS API to allow WebAssembly computations to suspend until a promise result from JS completes;
 2. In some future world, we may have access to primitives that can implement green threads / fibers in C++.  But that would be a future concern and not an immediate target of the C++ side of this proposal.

**Comment by tlively** [comment]
I took a look at the C++ coroutine story today and it looks like it would be pretty tricky to profitably use stack switching there, but possibly not impossible in special cases.

C++ coroutines are stackless. That by itself is not a problem; Kotlin coroutines are also stackless, but they can be implemented on top of stack switching anyway by putting handlers only at the transition from normal functions to suspend functions. Then frame-by-frame resumption and suspension can be transparently replaced with single `resume` and `suspend` operations.

The problem with C++ coroutines is that they are _observably_ stackless. Every suspension and resumption in every individual frame can run arbitrary user code, so you cannot just transparently replace them all with a single `suspend` or `resume`. I can imagine three ways to use stack switching anyway:

1. As a library, providing a custom awaitable type that would use stack switching intrinsics and would be able to interoperate with other coroutines, which would continue to be stackless state machines.
2. As an optimized lowering for coroutine types that suspend and resume without additional side effects. Handlers would have to be inserted wherever suspension is not simply propagated.
3. As the lowering for all coroutine suspensions and resumptions, with subsequent optimizations responsible for eliding handlers as in (2) and performing stack machine transformations on continuations known to be only one frame deep.

(1) Seems the most plausible, but also the least compelling because it would do nothing for code that doesn't use the new library and because it would essentially be a nonstandard language extension.

(3) Seems like it would be mostly straightforward, but then getting an actual performance improvement out of it would require heroic follow-on optimizations. This might also be a good code size optimization even if it is bad for performance.

(2) Seems similar to (3), except that it starts with the heroic optimizations out of the gate.
