### ISSUE TITLE
Mutable globals

### ISSUE THREAD

**Issue by verbessern** [WebAssembly/stack-switching#88]
When each function call can be suspended, and until it is resumed, an arbitrary number of instructions can be executed, then the value inside a mutable global can only be predicted between function calls. To ensure the value of a mutable global, it has to stored/loaded inside/from a local on every call, just in case. It looks to me that this makes the mutable globals far less usable the immutable globals, set during the initialization time.

**Comment by rossberg** [comment]
A call to an (unknown) function may already mutate globals, so this isn't a new property, is it?

**Comment by verbessern** [comment]
A mutable global's access in a program can be known recursively, with the stack switching now it has to be known and reentrantly. With other words, some use cases drop.

**Comment by verbessern** [comment]
```
fn foo()
{
  global.value = 5;
  call zoo() 
  global.value = 1;
}
fn zoo() {...} // never writes, but can read the global multiple times 
               // before and after an arbitrary number of stack switches
```
If inside zoo there is a stack switch, and foo is called from the new stack, it is possible that zoo will see 5 before the switch and 1 after it, because the global is clobbered.

**Comment by verbessern** [comment]
It seems you are right. My head spins from proposals and issues reading in the last days. Thank you. The globals are instance (thread) local storage, not coroutine local storage. I guess having "suspendable/green" globals is not a feature to have.
