### ISSUE TITLE
[reference interpreter] validation bug on switch with non-recursive type

### ISSUE THREAD

**Issue by frank-emrich** [WebAssembly/stack-switching#98]
Here's a simple example program using `switch` where we don't use a recursive type for the involved continuations:

``` wast
(module
 (type $ft0 (func))
 (type $ct0 (cont $ft0))

 (type $ft1 (func (param (ref $ct0))))
 (type $ct1 (cont $ft1))

 (tag $t)

 (func $f
   (cont.new $ct1 (ref.func $g))
   (switch $ct1 $t)
 )
 (elem declare func $f)

 (func $g (param (ref $ct0)))
 (elem declare func $g)

 (func $entry
   (cont.new $ct0 (ref.func $f))
   (resume $ct0 (on $t switch))
 )
)
```
From my understanding of the typing rules of `switch`, this should be accepted.

However, the reference interpreter rejects it with the following message (associated with the `switch` instruction):
```
type mismatch: instruction requires [(ref 1)] but stack has [(ref 3)]
```

**Comment by rossberg** [comment]
Yeah, in the implementation [here](https://github.com/WebAssembly/stack-switching/blob/8cd685b4d2463ae0fced8022d4aed06b9fbe842e/interpreter/valid/valid.ml#L641), the resulting type should probably be something like
```
(ts11 @ [RefT (Null, VarHT (StatX x.it))]) --> ts21, []
```
not just `ts11` on the left. But the first `require` check also looks funny, since it appears matching `ft` against itself.

@dhil, something is off, do you agree?

**Comment by dhil** [comment]
There is a bug. But your suggested fix is not correct. I believe the correct fix is

```ocaml
((Lib.List.lead ts11) @ [RefT (Null, VarHT (StatX x.it))]) --> ts21, []
```

We have to replace the current continuation from the argument list with the switched-to continuation. The current thing happens to be work when the "switcher" and "switchee" use the same continuation type. 

> But the first require check also looks funny, since it appears to be matching ft against its own definition?

It does not check against its own definition. It checks that the parameter list on the tag is empty.

```ocaml
     let FuncT (_, t) as ft = func_type_of_tag_type c et y.at in
     require (match_func_type c.types (FuncT ([] (* empty parameter list *), t)) ft) y.at
       "type mismatch in switch tag";
```

I suppose we do the following instead

```ocaml
     let FuncT (t1, t) = func_type_of_tag_type c et y.at in
     require (match_result_type c.types [] t1) y.at
       "type mismatch in switch tag";
```

I will open a PR with the fix shortly. There is actually another bug too...
